teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    axis_linear:
      x: 1    # Left Stick Up/Down
    scale_linear:
      x: 0.5
    axis_angular:
      yaw: 0  # Left Stick Left/Right
    scale_angular:
      yaw: 1.0
