"""Interactive Xbox-controller calibration for lupin_hmi teleop.

Why this exists
---------------
The button/axis index order an Xbox pad presents to ``joy_node`` (SDL2) depends
on the kernel driver, which depends on the transport: a USB cable binds
``xpad`` (standard layout) while Bluetooth binds the Microsoft-HID path (a
shifted layout). Switching between them silently remaps every control. This
tool re-probes the *currently connected* pad and rewrites the matching config
file (``config/xbox_config.{usb,bluetooth}.yaml``) that xbox_teleop loads.

What it does
------------
1. Detects whether the pad is on USB or Bluetooth (lupin_hmi.pad_detect).
2. Spawns its OWN joy_node (so the full teleop stack stays down and the robot
   can't move while you press buttons) and reads /joy.
3. Walks you through each control one at a time, detecting the index and — for
   sticks/D-pad/triggers — the direction, so the saved mapping reproduces the
   documented control scheme regardless of how the indices shifted.
4. Writes the matching mode file (with a .bak backup), leaving the other
   mode's file untouched.

Run it with the teleop launch STOPPED:

    ros2 run lupin_hmi calibrate_xbox

Useful flags: --mode {auto,usb,bluetooth}, --print-only, --device-id N,
--list, --yes, --force, --config-dir PATH.
"""

from __future__ import annotations

import argparse
import glob
import os
import shutil
import subprocess
import sys
import threading
import time

import rclpy
from rclpy.executors import SingleThreadedExecutor
from rclpy.node import Node
from sensor_msgs.msg import Joy

from ament_index_python.packages import get_package_share_directory

from lupin_hmi.pad_detect import detect_pad_mode, describe_pads


# ── config rendering ──────────────────────────────────────────────────────

# Built-in defaults used when the target file doesn't exist yet. Mirror the
# seed yamls so a --print-only run before any file exists still makes sense.
_DEFAULTS = {
    'usb': {
        'device_name': 'Xbox Series X Controller', 'device_id': 0, 'deadzone': 0.10,
        'enable_button': 4, 'enable_turbo_button': 5,
        'axis_linear_x': 1, 'axis_linear_y': 0, 'axis_angular_yaw': 3,
        'scale_linear_x': -0.2, 'scale_linear_y': -0.2,
        'scale_linear_turbo_x': -0.6, 'scale_linear_turbo_y': -0.6,
        'scale_angular_yaw': -0.7, 'scale_angular_turbo_yaw': -1.4,
        'shoulder_pan_plus_button': 1, 'shoulder_pan_minus_button': 2,
        'shoulder_lift_plus_button': 3, 'shoulder_lift_minus_button': 0,
        'elbow_axis': 7, 'wrist_axis': 6,
        'shoulder_disable_button': 4,
        'shoulder_pan_sign': 1, 'shoulder_lift_sign': 1,
        'elbow_sign': -1, 'wrist_sign': -1,
        'gripper_open_axis': -1, 'gripper_close_axis': -1,
        'gripper_open_rest': 0.0, 'gripper_open_full': 1.0,
        'gripper_close_rest': 0.0, 'gripper_close_full': 1.0,
    },
    'bluetooth': {
        'device_name': 'Xbox Series X Controller', 'device_id': 0, 'deadzone': 0.15,
        'enable_button': 6, 'enable_turbo_button': 7,
        'axis_linear_x': 1, 'axis_linear_y': 0, 'axis_angular_yaw': 2,
        'scale_linear_x': 0.2, 'scale_linear_y': 0.2,
        'scale_linear_turbo_x': 0.6, 'scale_linear_turbo_y': 0.6,
        'scale_angular_yaw': 0.7, 'scale_angular_turbo_yaw': 1.4,
        'shoulder_pan_plus_button': 1, 'shoulder_pan_minus_button': 3,
        'shoulder_lift_plus_button': 4, 'shoulder_lift_minus_button': 0,
        'elbow_axis': 7, 'wrist_axis': 6,
        'shoulder_disable_button': 6,
        'shoulder_pan_sign': 1, 'shoulder_lift_sign': 1,
        'elbow_sign': 1, 'wrist_sign': 1,
        'gripper_open_axis': 4, 'gripper_close_axis': 5,
        'gripper_open_rest': 1.0, 'gripper_open_full': -1.0,
        'gripper_close_rest': 1.0, 'gripper_close_full': -1.0,
    },
}


def _fmt(v) -> str:
    return f'{v:g}' if isinstance(v, float) else str(v)


def render_config(mode: str, m: dict) -> str:
    """Render the full params file (3 node sections) from a flat mapping dict."""
    g = lambda k: _fmt(m[k])  # noqa: E731
    return f"""# Xbox Wireless Controller — {mode.upper()} mapping.
# GENERATED by `ros2 run lupin_hmi calibrate_xbox`. Re-run it (with the pad on
# {mode}) to re-probe. xbox_teleop.launch.py auto-selects this file when the
# pad is on {mode}; the other transport uses xbox_config.{('bluetooth' if mode == 'usb' else 'usb')}.yaml.

joy_node:
  ros__parameters:
    device_name: "{m['device_name']}"
    device_id: {g('device_id')}
    deadzone: {g('deadzone')}

teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: {g('enable_button')}          # dead-man (hold to drive)
    enable_turbo_button: {g('enable_turbo_button')}    # turbo (hold to boost)

    axis_linear:
      x: {g('axis_linear_x')}                    # left stick → forward/back
      y: {g('axis_linear_y')}                    # left stick → strafe
    scale_linear:               # sign = stick-forward/left → robot forward/+y
      x: {g('scale_linear_x')}
      y: {g('scale_linear_y')}
    scale_linear_turbo:
      x: {g('scale_linear_turbo_x')}
      y: {g('scale_linear_turbo_y')}

    axis_angular:
      yaw: {g('axis_angular_yaw')}                  # right stick → yaw
    scale_angular:
      yaw: {g('scale_angular_yaw')}
    scale_angular_turbo:
      yaw: {g('scale_angular_turbo_yaw')}

arm_teleop:
  ros__parameters:
    shoulder_pan_axis: -1
    shoulder_lift_axis: -1
    shoulder_pan_plus_button: {g('shoulder_pan_plus_button')}
    shoulder_pan_minus_button: {g('shoulder_pan_minus_button')}
    shoulder_lift_plus_button: {g('shoulder_lift_plus_button')}
    shoulder_lift_minus_button: {g('shoulder_lift_minus_button')}
    elbow_axis: {g('elbow_axis')}                   # D-pad up/down → elbow ±
    wrist_axis: {g('wrist_axis')}                   # D-pad left/right → wrist ±
    elbow_plus_button: -1
    elbow_minus_button: -1
    wrist_plus_button: -1
    wrist_minus_button: -1
    shoulder_disable_button: {g('shoulder_disable_button')}      # silences arm while driving (= dead-man)
    shoulder_enable_button: -1
    shoulder_pan_sign: {g('shoulder_pan_sign')}
    shoulder_lift_sign: {g('shoulder_lift_sign')}
    elbow_sign: {g('elbow_sign')}
    wrist_sign: {g('wrist_sign')}
    gripper_open_axis: {g('gripper_open_axis')}            # RT
    gripper_close_axis: {g('gripper_close_axis')}           # LT
    gripper_open_rest: {g('gripper_open_rest')}
    gripper_open_full: {g('gripper_open_full')}
    gripper_close_rest: {g('gripper_close_rest')}
    gripper_close_full: {g('gripper_close_full')}
"""


def load_existing(path: str, mode: str) -> dict:
    """Flatten an existing mode file into the flat mapping dict, falling back
    to built-in defaults for anything missing/absent."""
    m = dict(_DEFAULTS[mode])
    try:
        import yaml
        with open(path) as fh:
            doc = yaml.safe_load(fh) or {}
    except (OSError, Exception):  # noqa: BLE001 - any parse issue → defaults
        return m

    joy = (doc.get('joy_node', {}) or {}).get('ros__parameters', {}) or {}
    tw = (doc.get('teleop_twist_joy_node', {}) or {}).get('ros__parameters', {}) or {}
    arm = (doc.get('arm_teleop', {}) or {}).get('ros__parameters', {}) or {}

    def setif(key, val):
        if val is not None:
            m[key] = val

    setif('device_name', joy.get('device_name'))
    setif('device_id', joy.get('device_id'))
    setif('deadzone', joy.get('deadzone'))
    setif('enable_button', tw.get('enable_button'))
    setif('enable_turbo_button', tw.get('enable_turbo_button'))
    setif('axis_linear_x', (tw.get('axis_linear') or {}).get('x'))
    setif('axis_linear_y', (tw.get('axis_linear') or {}).get('y'))
    setif('axis_angular_yaw', (tw.get('axis_angular') or {}).get('yaw'))
    setif('scale_linear_x', (tw.get('scale_linear') or {}).get('x'))
    setif('scale_linear_y', (tw.get('scale_linear') or {}).get('y'))
    setif('scale_linear_turbo_x', (tw.get('scale_linear_turbo') or {}).get('x'))
    setif('scale_linear_turbo_y', (tw.get('scale_linear_turbo') or {}).get('y'))
    setif('scale_angular_yaw', (tw.get('scale_angular') or {}).get('yaw'))
    setif('scale_angular_turbo_yaw', (tw.get('scale_angular_turbo') or {}).get('yaw'))
    for key in ('shoulder_pan_plus_button', 'shoulder_pan_minus_button',
                'shoulder_lift_plus_button', 'shoulder_lift_minus_button',
                'elbow_axis', 'wrist_axis', 'shoulder_disable_button',
                'shoulder_pan_sign', 'shoulder_lift_sign', 'elbow_sign', 'wrist_sign',
                'gripper_open_axis', 'gripper_close_axis',
                'gripper_open_rest', 'gripper_open_full',
                'gripper_close_rest', 'gripper_close_full'):
        setif(key, arm.get(key))
    return m


# ── joy reader node ───────────────────────────────────────────────────────

class JoyReader(Node):
    def __init__(self):
        super().__init__('calibrate_xbox')
        self._lock = threading.Lock()
        self._axes = None
        self._buttons = None
        self._count = 0
        self.create_subscription(Joy, '/joy', self._cb, 10)

    def _cb(self, msg: Joy) -> None:
        with self._lock:
            self._axes = list(msg.axes)
            self._buttons = list(msg.buttons)
            self._count += 1

    def snapshot(self):
        with self._lock:
            if self._axes is None:
                return None
            return list(self._axes), list(self._buttons), self._count


# ── detection / interaction ───────────────────────────────────────────────

class QuitCalibration(Exception):
    pass


class Calibrator:
    def __init__(self, reader: JoyReader, timeout: float = 8.0):
        self.r = reader
        self.timeout = timeout
        self.base_axes: list[float] = []
        self.base_buttons: list[int] = []

    # -- low-level waits --
    def capture_baseline(self, duration: float = 1.5) -> None:
        print('\nLeave everything CENTERED — sticks released, no buttons, '
              'triggers untouched.')
        input('  Press ENTER to capture the neutral baseline... ')
        samples = []
        end = time.monotonic() + duration
        while time.monotonic() < end:
            snap = self.r.snapshot()
            if snap is not None:
                samples.append(snap)
            time.sleep(0.02)
        if not samples:
            raise RuntimeError('no /joy messages during baseline capture')
        axes_last, btns_last, _ = samples[-1]
        n = len(axes_last)
        # Per-axis median over the window.
        self.base_axes = []
        for i in range(n):
            col = sorted(s[0][i] for s in samples if len(s[0]) > i)
            self.base_axes.append(col[len(col) // 2])
        self.base_buttons = list(btns_last)
        held = [i for i, b in enumerate(self.base_buttons) if b == 1]
        print(f'  baseline: {n} axes, {len(self.base_buttons)} buttons.'
              + (f'  WARNING: buttons {held} read as held.' if held else ''))

    def _wait_release_buttons(self, deadline_extra: float = 0.6) -> None:
        end = time.monotonic() + deadline_extra
        while time.monotonic() < end:
            snap = self.r.snapshot()
            if snap and not any(snap[1]):
                return
            time.sleep(0.02)

    def _wait_axis_settle(self, idx: int, extra: float = 0.8) -> None:
        end = time.monotonic() + extra
        while time.monotonic() < end:
            snap = self.r.snapshot()
            if snap and len(snap[0]) > idx \
                    and abs(snap[0][idx] - self.base_axes[idx]) < 0.3:
                return
            time.sleep(0.02)

    def detect_button(self):
        """Return the index of a single, stably-pressed button (or None)."""
        end = time.monotonic() + self.timeout
        cand = None
        since = 0.0
        while time.monotonic() < end:
            snap = self.r.snapshot()
            if snap is None:
                time.sleep(0.02)
                continue
            _, btns, _ = snap
            pressed = [i for i, b in enumerate(btns)
                       if b == 1 and (i >= len(self.base_buttons)
                                      or self.base_buttons[i] == 0)]
            if len(pressed) == 1:
                if cand == pressed[0]:
                    if time.monotonic() - since >= 0.12:
                        idx = cand
                        self._wait_release_buttons()
                        return idx
                else:
                    cand = pressed[0]
                    since = time.monotonic()
            else:
                cand = None
            time.sleep(0.02)
        return None

    def detect_axis(self, min_dev: float = 0.6):
        """Return (index, sign, value_at_deflection) for the most-deflected
        axis held past a threshold, or None."""
        end = time.monotonic() + self.timeout
        cand = None
        sign = 0
        since = 0.0
        while time.monotonic() < end:
            snap = self.r.snapshot()
            if snap is None:
                time.sleep(0.02)
                continue
            axes, _, _ = snap
            best_i, best_dev = None, 0.0
            for i, a in enumerate(axes):
                base = self.base_axes[i] if i < len(self.base_axes) else 0.0
                dev = a - base
                if abs(dev) > abs(best_dev):
                    best_i, best_dev = i, dev
            if best_i is not None and abs(best_dev) >= min_dev:
                s = 1 if best_dev > 0 else -1
                if cand == best_i and sign == s:
                    if time.monotonic() - since >= 0.12:
                        val = axes[best_i]
                        self._wait_axis_settle(best_i)
                        return best_i, s, val
                else:
                    cand, sign, since = best_i, s, time.monotonic()
            else:
                cand, sign = None, 0
            time.sleep(0.02)
        return None

    # -- step orchestration --
    def _step(self, title: str, instruction: str, detector):
        while True:
            print(f'\n▶ {title}')
            print(f'  {instruction}')
            choice = input('  ENTER = start  ·  s = skip (keep current)  ·  '
                           'q = quit: ').strip().lower()
            if choice == 'q':
                raise QuitCalibration
            if choice == 's':
                print('  → skipped (kept current value).')
                return None
            print('  … go! (waiting for input)')
            result = detector()
            if result is None:
                print('  ✗ nothing detected within the timeout.')
                again = input('  r = retry  ·  s = skip  ·  q = quit: ').strip().lower()
                if again == 'q':
                    raise QuitCalibration
                if again == 's':
                    return None
                continue
            print(f'  ✓ detected {self._describe(result)}')
            confirm = input('  ENTER = accept  ·  r = retry  ·  s = skip  ·  '
                            'q = quit: ').strip().lower()
            if confirm == '':
                return result
            if confirm == 'q':
                raise QuitCalibration
            if confirm == 's':
                return None
            # otherwise loop and retry

    @staticmethod
    def _describe(result) -> str:
        if isinstance(result, int):
            return f'buttons[{result}]'
        idx, sign, val = result
        return f'axes[{idx}]  (direction {"+" if sign > 0 else "-"}, value {val:+.2f})'

    def button_step(self, title, instruction):
        return self._step(title, instruction, self.detect_button)

    def axis_step(self, title, instruction):
        return self._step(title, instruction, self.detect_axis)

    def trigger_step(self, title, instruction):
        """Detect a trigger: index + fully-pulled value, then sample its true
        resting value (which joy_node only reports correctly after the first
        physical event). Returns (idx, rest, full) or None."""
        res = self._step(title, instruction, self.detect_axis)
        if res is None:
            return None
        idx, _sign, full = res
        print('  release the trigger and leave it alone…')
        time.sleep(1.2)
        snap = self.r.snapshot()
        rest = snap[0][idx] if snap and len(snap[0]) > idx else self.base_axes[idx]
        print(f'  rest={rest:+.2f}  full={full:+.2f}')
        return idx, rest, full


def run_walk(cal: Calibrator, m: dict) -> dict:
    """Run the full interactive sequence, overlaying detected values onto m."""
    cal.capture_baseline()

    # Drive — buttons
    b = cal.button_step('Dead-man (LB)',
                        'Press & HOLD the LEFT BUMPER (LB) — the button you hold to drive.')
    if b is not None:
        m['enable_button'] = b
        m['shoulder_disable_button'] = b  # same physical button by design
    b = cal.button_step('Turbo (RB)',
                        'Press & HOLD the RIGHT BUMPER (RB) — the boost button.')
    if b is not None:
        m['enable_turbo_button'] = b

    # Drive — sticks (direction matters)
    r = cal.axis_step('Left stick — FORWARD',
                      'Push the LEFT stick fully FORWARD and hold.')
    if r:
        idx, sign, _ = r
        m['axis_linear_x'] = idx
        m['scale_linear_x'] = sign * abs(m['scale_linear_x'] or 0.2)
        m['scale_linear_turbo_x'] = sign * abs(m['scale_linear_turbo_x'] or 0.6)
    r = cal.axis_step('Left stick — LEFT (strafe)',
                      'Push the LEFT stick fully to the LEFT and hold.')
    if r:
        idx, sign, _ = r
        m['axis_linear_y'] = idx
        m['scale_linear_y'] = sign * abs(m['scale_linear_y'] or 0.2)
        m['scale_linear_turbo_y'] = sign * abs(m['scale_linear_turbo_y'] or 0.6)
    r = cal.axis_step('Right stick — LEFT (turn left)',
                      'Push the RIGHT stick fully to the LEFT (turn-in-place left) and hold.')
    if r:
        idx, sign, _ = r
        m['axis_angular_yaw'] = idx
        m['scale_angular_yaw'] = sign * abs(m['scale_angular_yaw'] or 0.7)
        m['scale_angular_turbo_yaw'] = sign * abs(m['scale_angular_turbo_yaw'] or 1.4)

    # Arm — face buttons (direction is the button, no sign)
    for key, title, instr in (
        ('shoulder_pan_plus_button', 'Shoulder PAN +', 'Press the RIGHT face button (B) → pan +.'),
        ('shoulder_pan_minus_button', 'Shoulder PAN -', 'Press the LEFT face button (X) → pan -.'),
        ('shoulder_lift_plus_button', 'Shoulder LIFT +', 'Press the TOP face button (Y) → lift +.'),
        ('shoulder_lift_minus_button', 'Shoulder LIFT -', 'Press the BOTTOM face button (A) → lift -.'),
    ):
        b = cal.button_step(title, instr)
        if b is not None:
            m[key] = b

    # Arm — D-pad axes (direction → joint +)
    r = cal.axis_step('Elbow (D-pad UP)', 'Press & hold the D-pad UP.')
    if r:
        idx, sign, _ = r
        m['elbow_axis'] = idx
        m['elbow_sign'] = sign
    r = cal.axis_step('Wrist (D-pad LEFT)', 'Press & hold the D-pad LEFT.')
    if r:
        idx, sign, _ = r
        m['wrist_axis'] = idx
        m['wrist_sign'] = sign

    # Gripper — triggers (index + rest/full)
    t = cal.trigger_step('Gripper OPEN (RT)', 'Pull the RIGHT trigger (RT) fully and hold.')
    if t:
        idx, rest, full = t
        m['gripper_open_axis'] = idx
        m['gripper_open_rest'] = float(rest)
        m['gripper_open_full'] = float(full)
    t = cal.trigger_step('Gripper CLOSE (LT)', 'Pull the LEFT trigger (LT) fully and hold.')
    if t:
        idx, rest, full = t
        m['gripper_close_axis'] = idx
        m['gripper_close_rest'] = float(rest)
        m['gripper_close_full'] = float(full)
    return m


def warn_collisions(m: dict) -> None:
    axis_uses = {
        'left-stick fwd/back': m['axis_linear_x'],
        'left-stick strafe': m['axis_linear_y'],
        'right-stick yaw': m['axis_angular_yaw'],
        'elbow D-pad': m['elbow_axis'],
        'wrist D-pad': m['wrist_axis'],
    }
    seen = {}
    for name, idx in axis_uses.items():
        seen.setdefault(idx, []).append(name)
    dupes = {i: names for i, names in seen.items() if len(names) > 1}
    if dupes:
        print('\n⚠  axis collisions (same index used twice):')
        for i, names in dupes.items():
            print(f'     axes[{i}] ← {", ".join(names)}')
    btn_uses = {
        'pan+': m['shoulder_pan_plus_button'], 'pan-': m['shoulder_pan_minus_button'],
        'lift+': m['shoulder_lift_plus_button'], 'lift-': m['shoulder_lift_minus_button'],
        'turbo': m['enable_turbo_button'],
    }
    seen = {}
    for name, idx in btn_uses.items():
        seen.setdefault(idx, []).append(name)
    dupes = {i: names for i, names in seen.items() if len(names) > 1}
    if dupes:
        print('⚠  button collisions:')
        for i, names in dupes.items():
            print(f'     buttons[{i}] ← {", ".join(names)}')


# ── SDL device enumeration ────────────────────────────────────────────────

def enumerate_sdl_devices() -> list:
    try:
        out = subprocess.run(['ros2', 'run', 'joy', 'joy_enumerate_devices'],
                             capture_output=True, text=True, timeout=25)
    except (subprocess.SubprocessError, OSError):
        return []
    devs = []
    for line in out.stdout.splitlines():
        parts = [p.strip() for p in line.split(':')]
        if len(parts) >= 5 and parts[0].isdigit():
            devs.append({
                'id': int(parts[0]),
                'gamepad': parts[2].lower() == 'true',
                'name': ':'.join(parts[4:]).strip(),
            })
    return devs


def choose_device(forced_id):
    devs = enumerate_sdl_devices()
    if forced_id is not None:
        name = next((d['name'] for d in devs if d['id'] == forced_id), 'unknown')
        return forced_id, name
    if not devs:
        print('  (could not enumerate SDL devices — assuming device_id 0)')
        return 0, 'unknown'
    pads = [d for d in devs if d['gamepad']] or devs
    if len(pads) == 1:
        print(f"  using SDL device {pads[0]['id']}: {pads[0]['name']}")
        return pads[0]['id'], pads[0]['name']
    print('\nMultiple controllers found:')
    for d in pads:
        print(f"   [{d['id']}] {d['name']}{'  (gamepad)' if d['gamepad'] else ''}")
    while True:
        sel = input('  Pick device id: ').strip()
        if sel.isdigit() and any(d['id'] == int(sel) for d in pads):
            chosen = next(d for d in pads if d['id'] == int(sel))
            return chosen['id'], chosen['name']


# ── write-out ─────────────────────────────────────────────────────────────

def _source_config_dirs(runtime_path: str) -> list:
    """Best-effort locate the SOURCE config dir(s) so calibration persists
    across a clean rebuild (the runtime copy lives in build/ via a symlink)."""
    dirs = []
    # (a) Derived from this module's real location — hits when the installed
    #     python package is symlinked back to src.
    try:
        cand = os.path.normpath(os.path.join(
            os.path.dirname(os.path.realpath(__file__)), '..', 'config'))
        if os.path.isdir(cand):
            dirs.append(cand)
    except OSError:
        pass
    # (b) Walk up from the runtime copy (…/build|install/lupin_hmi/config) to
    #     the workspace root, then find src/**/lupin_hmi/config.
    real = os.path.realpath(runtime_path)
    for marker in ('/build/', '/install/'):
        if marker in real:
            ws = real.split(marker)[0]
            for cand in glob.glob(os.path.join(ws, 'src', '**', 'lupin_hmi', 'config'),
                                  recursive=True):
                if os.path.isdir(cand):
                    dirs.append(cand)
            break
    return dirs


def write_config(text: str, config_dir: str, mode: str) -> list:
    """Write the live runtime copy and any locatable source copy, backing up
    existing files. Returns [(path, kind), …] with kind in {'runtime','source'}."""
    fname = f'xbox_config.{mode}.yaml'
    runtime_path = os.path.join(config_dir, fname)
    targets = [(runtime_path, 'runtime')]
    for src_dir in _source_config_dirs(runtime_path):
        targets.append((os.path.join(src_dir, fname), 'source'))

    written, seen = [], set()
    for path, kind in targets:
        real = os.path.realpath(path)
        if real in seen:
            continue
        seen.add(real)
        if os.path.exists(path):
            shutil.copy2(path, path + '.bak')
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as fh:
            fh.write(text)
        written.append((path, kind))
    return written


# ── main ──────────────────────────────────────────────────────────────────

def main(args=None) -> int:
    parser = argparse.ArgumentParser(
        prog='calibrate_xbox', description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--mode', choices=['auto', 'usb', 'bluetooth'], default='auto',
                        help='Which mapping to calibrate. auto = detect transport.')
    parser.add_argument('--config-dir', default=None,
                        help='Override the config dir (default: lupin_hmi share/config).')
    parser.add_argument('--device-id', type=int, default=None,
                        help='Force the SDL device id (skip enumeration prompt).')
    parser.add_argument('--timeout', type=float, default=8.0,
                        help='Per-control detection timeout in seconds (default 8).')
    parser.add_argument('--print-only', action='store_true',
                        help='Print the resulting file instead of writing it.')
    parser.add_argument('--yes', action='store_true',
                        help='Skip the final confirmation prompt.')
    parser.add_argument('--force', action='store_true',
                        help='Skip the "is teleop running?" safety check.')
    parser.add_argument('--list', action='store_true',
                        help='List detected pads + SDL devices and exit.')
    opts = parser.parse_args(args=args)

    if opts.list:
        print('Transport detection:', describe_pads())
        print('Detected mode      :', detect_pad_mode())
        print('SDL devices:')
        for d in enumerate_sdl_devices():
            print(f"   [{d['id']}] {d['name']}  gamepad={d['gamepad']}")
        return 0

    # Resolve mode.
    mode = opts.mode
    if mode == 'auto':
        detected = detect_pad_mode()
        print(f'Transport detection: {describe_pads()}')
        if detected is None:
            print('Could not detect the transport. Re-run with --mode usb|bluetooth.')
            return 2
        mode = detected
    print(f'\n=== Calibrating the {mode.upper()} mapping ===')

    config_dir = opts.config_dir or os.path.join(
        get_package_share_directory('lupin_hmi'), 'config')
    target = os.path.join(config_dir, f'xbox_config.{mode}.yaml')
    m = load_existing(target, mode)

    # Pick the SDL device for our own joy_node.
    device_id, device_name = choose_device(opts.device_id)
    m['device_id'] = device_id
    if device_name and device_name != 'unknown':
        m['device_name'] = device_name

    print('\n⚠  Make sure xbox_teleop is STOPPED (Ctrl-C the teleop launch).')
    print('   This tool runs its own joy_node; if teleop is up the robot will')
    print('   move while you press buttons.')
    input('   Press ENTER once teleop is stopped… ')

    rclpy.init()
    reader = JoyReader()
    executor = SingleThreadedExecutor()
    executor.add_node(reader)
    spin = threading.Thread(target=executor.spin, daemon=True)
    spin.start()

    joy_proc = None
    rc = 0
    try:
        # Best-effort safety check (graph discovery; may be blind under some
        # DDS setups, hence the explicit prompt above).
        time.sleep(1.5)
        if not opts.force:
            names = reader.get_node_names()
            clashing = [n for n in ('arm_teleop', 'teleop_twist_joy_node') if n in names]
            if clashing:
                print(f'\n✗ teleop appears to be running ({", ".join(clashing)}). '
                      'Stop it first, or pass --force.')
                return 3

        # Spawn our own joy_node (raw: deadzone 0 so we see true axis values).
        joy_proc = subprocess.Popen(
            ['ros2', 'run', 'joy', 'joy_node', '--ros-args',
             '-r', '__node:=calibrate_joy_node',
             '-p', f'device_id:={device_id}',
             '-p', 'deadzone:=0.0',
             '-p', 'autorepeat_rate:=20.0'],
            stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)

        print('\nStarting joy_node and waiting for /joy…')
        deadline = time.monotonic() + 6.0
        while time.monotonic() < deadline and reader.snapshot() is None:
            if joy_proc.poll() is not None:
                err = (joy_proc.stderr.read() or '').strip()
                print(f'✗ joy_node exited early.\n{err}')
                return 4
            time.sleep(0.1)
        if reader.snapshot() is None:
            print('✗ no /joy messages. Is the pad on and is the SDL device id '
                  'right? Try `--list`.')
            return 4

        try:
            m = run_walk(Calibrator(reader, timeout=opts.timeout), m)
        except QuitCalibration:
            print('\nAborted — nothing written.')
            return 1

        warn_collisions(m)
        text = render_config(mode, m)
        print('\n' + '─' * 70)
        print(text.rstrip())
        print('─' * 70)

        if opts.print_only:
            print('\n(--print-only: not writing)')
            return 0
        if not opts.yes:
            ans = input(f'\nWrite this to xbox_config.{mode}.yaml? [y/N] ').strip().lower()
            if ans not in ('y', 'yes'):
                print('Not written.')
                return 0

        written = write_config(text, config_dir, mode)
        print('\n✓ wrote:')
        for path, kind in written:
            tag = 'live now' if kind == 'runtime' else 'source — persists rebuilds'
            print(f'   [{kind:7}] {path}  ({tag})')
        wrote_source = any(k == 'source' for _, k in written)
        print('\nNext: relaunch teleop —  ros2 launch lupin_hmi xbox_teleop.launch.py')
        if not wrote_source:
            print('NOTE: could not locate the source copy — a clean rebuild would revert')
            print('      this. Save the YAML printed above to '
                  f'src/.../lupin_hmi/config/xbox_config.{mode}.yaml to persist it.')
    finally:
        if joy_proc is not None:
            joy_proc.terminate()
            try:
                joy_proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                joy_proc.kill()
        executor.shutdown()
        reader.destroy_node()
        rclpy.shutdown()
    return rc


if __name__ == '__main__':
    sys.exit(main())
