#!/usr/bin/env bash
# setup-laptop-dds-env.sh — wire the laptop's ROS 2 to the robot's FastDDS
# discovery server so participants can find each other over WiFi.
#
# What this does:
#   1. Generates ~/.config/lupin/fastdds_super_client.xml from the in-tree
#      template, substituting the robot's IP.
#   2. Writes ~/.config/lupin/ros-env.sh that exports the three env vars
#      FastDDS 2.6 needs (FASTRTPS_DEFAULT_PROFILES_FILE,
#      ROS_DISCOVERY_SERVER, RMW_IMPLEMENTATION) and kills any stale
#      ros2 daemon so the next CLI re-reads them.
#   3. Adds a source line to ~/.bashrc (once; idempotent).
#
# Why XML + env var both: on Humble's FastDDS 2.6, either alone is flaky —
# the XML alone won't auto-connect to the server, and ROS_DISCOVERY_SERVER
# env alone won't apply SUPER_CLIENT semantics. Both in the daemon's
# environment is the only reliable combination.
#
# Usage:
#   ./setup-laptop-dds-env.sh                       # uses 192.168.42.1 (robot's own AP)
#   ./setup-laptop-dds-env.sh 10.42.0.42            # custom robot IP
#   ROBOT_IP=192.168.1.50 ./setup-laptop-dds-env.sh # also accepts env var
#   ./setup-laptop-dds-env.sh --uninstall           # remove .bashrc hook and generated configs
#
# The robot side is configured separately via `MIRTE_FASTDDS=true` in
# `~/.mirte_settings.sh` — that flips the vendor's mirte_ros.sh into
# starting `fast-discovery-server` on UDP :11811 at boot.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/../config/fastdds_super_client.xml.in"

# When installed via colcon, the script ships under share/lupin_bringup/scripts
# and the template under share/lupin_bringup/config — same relative path.
if [[ ! -f "${TEMPLATE}" ]]; then
  echo "error: template not found at ${TEMPLATE}" >&2
  exit 1
fi

DEFAULT_ROBOT_IP="192.168.42.1"
ROBOT_IP="${ROBOT_IP:-${DEFAULT_ROBOT_IP}}"
ACTION="install"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall) ACTION="uninstall"; shift ;;
    -h|--help)
      sed -n '2,30p' "$0"
      exit 0
      ;;
    *)
      if [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        ROBOT_IP="$1"
      else
        echo "error: unrecognised arg '$1'" >&2
        exit 2
      fi
      shift
      ;;
  esac
done

CONFIG_DIR="${HOME}/.config/lupin"
PROFILE_OUT="${CONFIG_DIR}/fastdds_super_client.xml"
ENV_OUT="${CONFIG_DIR}/ros-env.sh"
BASHRC="${HOME}/.bashrc"
BASHRC_MARK="# Lupin DDS env (sourced by lupin_bringup/scripts/setup-laptop-dds-env.sh)"

uninstall() {
  rm -f "${PROFILE_OUT}" "${ENV_OUT}"
  # Strip our two-line block from ~/.bashrc if present.
  if grep -Fq "${BASHRC_MARK}" "${BASHRC}" 2>/dev/null; then
    sed -i.lupin-bak "/${BASHRC_MARK//\//\\/}/,+1d" "${BASHRC}"
    echo "  removed bashrc hook (backup at ${BASHRC}.lupin-bak)"
  fi
  echo "uninstalled."
}

if [[ "${ACTION}" == "uninstall" ]]; then
  uninstall
  exit 0
fi

mkdir -p "${CONFIG_DIR}"

# 1. Generate the per-robot XML profile.
sed "s/@ROBOT_IP@/${ROBOT_IP}/g" "${TEMPLATE}" > "${PROFILE_OUT}"
chmod 0644 "${PROFILE_OUT}"

# 2. Write the env-loader (sourced by bashrc, also usable standalone).
#    Important: NO side effects in this script — pure env exports. Earlier
#    versions included a `pkill ros2cli.daemon` ("one-time transition reset")
#    here, but since the script is sourced by every new terminal it ended up
#    killing the running daemon on every shell start. Subsequent terminals
#    then saw the empty 2-topic state until they manually `ros2 daemon start`.
#    The one-time reset belongs in laptop-hygiene step 2 of DEMO_DAY.md, not
#    in the per-terminal env loader. (See feedback_no_daemon_thrash.)
cat > "${ENV_OUT}" <<EOF
# Auto-generated by setup-laptop-dds-env.sh — re-run that script to update.
# Robot at ${ROBOT_IP}; edit and re-run with a new IP if the robot moves.
# Pure env exports — no side effects (no daemon kill, no daemon start).
# Sourced by every new terminal, so any side effect would amplify per shell.
export FASTRTPS_DEFAULT_PROFILES_FILE="${PROFILE_OUT}"
export ROS_DISCOVERY_SERVER="${ROBOT_IP}:11811"
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
EOF
chmod 0644 "${ENV_OUT}"

# 3. Wire ~/.bashrc to source it (idempotent).
if ! grep -Fq "${BASHRC_MARK}" "${BASHRC}" 2>/dev/null; then
  {
    echo ""
    echo "${BASHRC_MARK}"
    echo "[ -f \"${ENV_OUT}\" ] && source \"${ENV_OUT}\""
  } >> "${BASHRC}"
  echo "  added source line to ${BASHRC}"
fi

cat <<EOF

installed:
  profile  ${PROFILE_OUT}
  env      ${ENV_OUT}
  bashrc   hooked (search: '${BASHRC_MARK}')
  robot IP ${ROBOT_IP}

Open a new shell (or 'source ${ENV_OUT}') before running 'ros2 launch ...'.

To verify the link is live (robot must be booted with MIRTE_FASTDDS=true):
  source ${ENV_OUT}
  ros2 daemon start && sleep 5
  ros2 topic list | wc -l            # expect 50+, not 2
  ros2 topic echo /io/power/power_watcher --once
EOF
